/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gui;

import dao.ClienteDAO;
import java.util.ArrayList;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import model.Cliente;
import utils.GerenteDeImagens;

public class ClienteGUI extends javax.swing.JFrame {

    List<Cliente> listaClientes = new ArrayList<Cliente>();
    GerenteDeImagens gerenteDeImagens = new GerenteDeImagens();
    ClienteDAO clienteDAO = new ClienteDAO();
    //private JTable table;
    //DefaultTableModel modelo = new DefaultTableModel();

    /**
     * Creates new form ClienteGUI
     */
    public ClienteGUI() throws ClassNotFoundException {
        this.clienteDAO = new ClienteDAO();
        initComponents();
        setLocationRelativeTo(null);
        listaClientes = new ArrayList();
//        clienteDAO = new ClienteDAO();
        listaClientes = clienteDAO.getAll();
        //CarregarTabelaClientes();
//        botaoSalvar.setEnabled(false);
//        botaoExcluir.setEnabled(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jComboBox1 = new javax.swing.JComboBox<>();
        buttonGroup2 = new javax.swing.ButtonGroup();
        buttonGroup3 = new javax.swing.ButtonGroup();
        buttonGroup4 = new javax.swing.ButtonGroup();
        buttonGroup5 = new javax.swing.ButtonGroup();
        buttonGroup6 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        campoMasculino = new javax.swing.JRadioButton();
        campoFeminino = new javax.swing.JRadioButton();
        campoNome = new javax.swing.JTextField();
        campoEmail = new javax.swing.JTextField();
        campoTelefone = new javax.swing.JTextField();
        campoImagemCliente = new javax.swing.JLabel();
        campoNumero = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        campoBairro = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        campoRua = new javax.swing.JTextField();
        jLabelHorarios = new javax.swing.JLabel();
        jPanelSegundaFeira = new javax.swing.JPanel();
        jRadioButtonSeisSegunda = new javax.swing.JRadioButton();
        jRadioButtonSeteSegunda = new javax.swing.JRadioButton();
        jRadioButtonOitoSegunda = new javax.swing.JRadioButton();
        jRadioButtonDezesseisSegunda = new javax.swing.JRadioButton();
        jRadioButtonDezesseteSegunda = new javax.swing.JRadioButton();
        jRadioButtonDezoitoSegunda = new javax.swing.JRadioButton();
        jRadioButtonDezenoveSegunda = new javax.swing.JRadioButton();
        jPanelTercaFeira = new javax.swing.JPanel();
        jRadioButtonSeisTerca = new javax.swing.JRadioButton();
        jRadioButtonSeteTerca = new javax.swing.JRadioButton();
        jRadioButtonOitoTerca = new javax.swing.JRadioButton();
        jRadioButtonDezesseisTerca = new javax.swing.JRadioButton();
        jRadioButtonDezesseteTerca = new javax.swing.JRadioButton();
        jRadioButtonDezoitoTerca = new javax.swing.JRadioButton();
        jRadioButtonDezenoveTerca = new javax.swing.JRadioButton();
        jPanelQuartaFeira = new javax.swing.JPanel();
        jRadioButtonSeisQuarta = new javax.swing.JRadioButton();
        jRadioButtonSeteQuarta = new javax.swing.JRadioButton();
        jRadioButtonOitoQuarta = new javax.swing.JRadioButton();
        jRadioButtonDezesseisQuarta = new javax.swing.JRadioButton();
        jRadioButtonDezesseteQuarta = new javax.swing.JRadioButton();
        jRadioButtonDezoitoQuarta = new javax.swing.JRadioButton();
        jRadioButtonDezenoveQuarta = new javax.swing.JRadioButton();
        jPanelQuintaFeira = new javax.swing.JPanel();
        jRadioButtonSeisQuinta = new javax.swing.JRadioButton();
        jRadioButtonSeteQuinta = new javax.swing.JRadioButton();
        jRadioButtonOitoQuinta = new javax.swing.JRadioButton();
        jRadioButtonDezesseisQuinta = new javax.swing.JRadioButton();
        jRadioButtonDezesseteQuinta = new javax.swing.JRadioButton();
        jRadioButtonDezoitoQuinta = new javax.swing.JRadioButton();
        jRadioButtonDezenoveQuinta = new javax.swing.JRadioButton();
        jPanelSextaFeira = new javax.swing.JPanel();
        jRadioButtonSeisSexta = new javax.swing.JRadioButton();
        jRadioButtonSeteSexta = new javax.swing.JRadioButton();
        jRadioButtonOitoSexta = new javax.swing.JRadioButton();
        jRadioButtonDezesseisSexta = new javax.swing.JRadioButton();
        jRadioButtonDezesseteSexta = new javax.swing.JRadioButton();
        jRadioButtonDezoitoSexta = new javax.swing.JRadioButton();
        jRadioButtonDezenoveSexta = new javax.swing.JRadioButton();
        jFormattedTextFieldDataMatricula = new javax.swing.JFormattedTextField();
        jLabel6 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        botaoSalvar = new javax.swing.JButton();
        botaoListar = new javax.swing.JButton();

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Cadastro Clientes");
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel1.setMaximumSize(new java.awt.Dimension(50000, 32767));
        jPanel1.setPreferredSize(new java.awt.Dimension(800, 600));

        jLabel1.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(65, 132, 234));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Cadastro de Clientes");
        jLabel1.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jLabel1.setMaximumSize(new java.awt.Dimension(200, 30));
        jLabel1.setMinimumSize(new java.awt.Dimension(200, 30));
        jLabel1.setPreferredSize(new java.awt.Dimension(200, 30));

        jLabel2.setFont(new java.awt.Font("Arial Rounded MT Bold", 1, 11)); // NOI18N
        jLabel2.setText("Nome");

        jLabel3.setFont(new java.awt.Font("Arial Rounded MT Bold", 1, 11)); // NOI18N
        jLabel3.setText("Telefone");

        jLabel4.setFont(new java.awt.Font("Arial Rounded MT Bold", 1, 11)); // NOI18N
        jLabel4.setText("e-mail");

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Sexo", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Arial Rounded MT Bold", 1, 11))); // NOI18N

        campoMasculino.setBackground(new java.awt.Color(255, 255, 255));
        buttonGroup1.add(campoMasculino);
        campoMasculino.setText("Masculino");

        campoFeminino.setBackground(new java.awt.Color(255, 255, 255));
        buttonGroup1.add(campoFeminino);
        campoFeminino.setText("Feminino");
        campoFeminino.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                campoFemininoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap(20, Short.MAX_VALUE)
                .addComponent(campoMasculino)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(campoFeminino)
                .addGap(16, 16, 16))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(campoMasculino)
                .addComponent(campoFeminino))
        );

        campoNome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                campoNomeActionPerformed(evt);
            }
        });

        campoImagemCliente.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        campoImagemCliente.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imgs/cliente.png"))); // NOI18N
        campoImagemCliente.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        campoImagemCliente.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                campoImagemClienteMouseClicked(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Arial Rounded MT Bold", 1, 11)); // NOI18N
        jLabel5.setText("Rua");

        jLabel7.setFont(new java.awt.Font("Arial Rounded MT Bold", 1, 11)); // NOI18N
        jLabel7.setText("nº");

        jLabel8.setFont(new java.awt.Font("Arial Rounded MT Bold", 1, 11)); // NOI18N
        jLabel8.setText("Bairro");

        jLabelHorarios.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabelHorarios.setText(" Cadastro de horário das Aulas");
        jLabelHorarios.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jPanelSegundaFeira.setBackground(new java.awt.Color(255, 255, 255));
        jPanelSegundaFeira.setBorder(javax.swing.BorderFactory.createTitledBorder("Segunda - feira"));

        jRadioButtonSeisSegunda.setBackground(new java.awt.Color(255, 255, 255));
        jRadioButtonSeisSegunda.setText("06:00h");
        jRadioButtonSeisSegunda.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButtonSeisSegundaActionPerformed(evt);
            }
        });

        jRadioButtonSeteSegunda.setBackground(new java.awt.Color(255, 255, 255));
        jRadioButtonSeteSegunda.setText("07:00h");

        jRadioButtonOitoSegunda.setBackground(new java.awt.Color(255, 255, 255));
        jRadioButtonOitoSegunda.setText("08:00h");

        jRadioButtonDezesseisSegunda.setBackground(new java.awt.Color(255, 255, 255));
        jRadioButtonDezesseisSegunda.setText("16:00h");

        jRadioButtonDezesseteSegunda.setBackground(new java.awt.Color(255, 255, 255));
        jRadioButtonDezesseteSegunda.setText("17:00h");

        jRadioButtonDezoitoSegunda.setBackground(new java.awt.Color(255, 255, 255));
        jRadioButtonDezoitoSegunda.setText("18:00h");
        jRadioButtonDezoitoSegunda.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButtonDezoitoSegundaActionPerformed(evt);
            }
        });

        jRadioButtonDezenoveSegunda.setBackground(new java.awt.Color(255, 255, 255));
        jRadioButtonDezenoveSegunda.setText("19:00h");

        javax.swing.GroupLayout jPanelSegundaFeiraLayout = new javax.swing.GroupLayout(jPanelSegundaFeira);
        jPanelSegundaFeira.setLayout(jPanelSegundaFeiraLayout);
        jPanelSegundaFeiraLayout.setHorizontalGroup(
            jPanelSegundaFeiraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelSegundaFeiraLayout.createSequentialGroup()
                .addContainerGap(28, Short.MAX_VALUE)
                .addGroup(jPanelSegundaFeiraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jRadioButtonSeisSegunda, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jRadioButtonSeteSegunda, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jRadioButtonOitoSegunda, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jRadioButtonDezesseisSegunda, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jRadioButtonDezesseteSegunda, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jRadioButtonDezoitoSegunda, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jRadioButtonDezenoveSegunda, javax.swing.GroupLayout.Alignment.TRAILING))
                .addContainerGap())
        );
        jPanelSegundaFeiraLayout.setVerticalGroup(
            jPanelSegundaFeiraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelSegundaFeiraLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jRadioButtonSeisSegunda)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jRadioButtonSeteSegunda)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jRadioButtonOitoSegunda)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jRadioButtonDezesseisSegunda, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jRadioButtonDezesseteSegunda)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jRadioButtonDezoitoSegunda)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jRadioButtonDezenoveSegunda))
        );

        jPanelTercaFeira.setBackground(new java.awt.Color(255, 255, 255));
        jPanelTercaFeira.setBorder(javax.swing.BorderFactory.createTitledBorder("Terça - feira"));
        jPanelTercaFeira.setPreferredSize(new java.awt.Dimension(105, 209));

        jRadioButtonSeisTerca.setBackground(new java.awt.Color(255, 255, 255));
        jRadioButtonSeisTerca.setText("06:00h");

        jRadioButtonSeteTerca.setBackground(new java.awt.Color(255, 255, 255));
        jRadioButtonSeteTerca.setText("07:00h");

        jRadioButtonOitoTerca.setBackground(new java.awt.Color(255, 255, 255));
        jRadioButtonOitoTerca.setText("08:00h");

        jRadioButtonDezesseisTerca.setBackground(new java.awt.Color(255, 255, 255));
        jRadioButtonDezesseisTerca.setText("16:00h");

        jRadioButtonDezesseteTerca.setBackground(new java.awt.Color(255, 255, 255));
        jRadioButtonDezesseteTerca.setText("17:00h");

        jRadioButtonDezoitoTerca.setBackground(new java.awt.Color(255, 255, 255));
        jRadioButtonDezoitoTerca.setText("18:00h");

        jRadioButtonDezenoveTerca.setBackground(new java.awt.Color(255, 255, 255));
        jRadioButtonDezenoveTerca.setText("19:00h");

        javax.swing.GroupLayout jPanelTercaFeiraLayout = new javax.swing.GroupLayout(jPanelTercaFeira);
        jPanelTercaFeira.setLayout(jPanelTercaFeiraLayout);
        jPanelTercaFeiraLayout.setHorizontalGroup(
            jPanelTercaFeiraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelTercaFeiraLayout.createSequentialGroup()
                .addContainerGap(28, Short.MAX_VALUE)
                .addGroup(jPanelTercaFeiraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jRadioButtonDezesseisTerca, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jRadioButtonSeisTerca, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jRadioButtonSeteTerca, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jRadioButtonOitoTerca, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jRadioButtonDezesseteTerca, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jRadioButtonDezoitoTerca, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jRadioButtonDezenoveTerca, javax.swing.GroupLayout.Alignment.TRAILING))
                .addContainerGap())
        );
        jPanelTercaFeiraLayout.setVerticalGroup(
            jPanelTercaFeiraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelTercaFeiraLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jRadioButtonSeisTerca)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jRadioButtonSeteTerca)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jRadioButtonOitoTerca)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jRadioButtonDezesseisTerca)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jRadioButtonDezesseteTerca)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jRadioButtonDezoitoTerca)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jRadioButtonDezenoveTerca))
        );

        jPanelQuartaFeira.setBackground(new java.awt.Color(255, 255, 255));
        jPanelQuartaFeira.setBorder(javax.swing.BorderFactory.createTitledBorder("Quarta - feira"));
        jPanelQuartaFeira.setPreferredSize(new java.awt.Dimension(105, 209));

        jRadioButtonSeisQuarta.setBackground(new java.awt.Color(255, 255, 255));
        jRadioButtonSeisQuarta.setText("06:00h");

        jRadioButtonSeteQuarta.setBackground(new java.awt.Color(255, 255, 255));
        jRadioButtonSeteQuarta.setText("07:00h");

        jRadioButtonOitoQuarta.setBackground(new java.awt.Color(255, 255, 255));
        jRadioButtonOitoQuarta.setText("08:00h");

        jRadioButtonDezesseisQuarta.setBackground(new java.awt.Color(255, 255, 255));
        jRadioButtonDezesseisQuarta.setText("16:00h");

        jRadioButtonDezesseteQuarta.setBackground(new java.awt.Color(255, 255, 255));
        jRadioButtonDezesseteQuarta.setText("17:00h");

        jRadioButtonDezoitoQuarta.setBackground(new java.awt.Color(255, 255, 255));
        jRadioButtonDezoitoQuarta.setText("18:00h");

        jRadioButtonDezenoveQuarta.setBackground(new java.awt.Color(255, 255, 255));
        jRadioButtonDezenoveQuarta.setText("19:00h");

        javax.swing.GroupLayout jPanelQuartaFeiraLayout = new javax.swing.GroupLayout(jPanelQuartaFeira);
        jPanelQuartaFeira.setLayout(jPanelQuartaFeiraLayout);
        jPanelQuartaFeiraLayout.setHorizontalGroup(
            jPanelQuartaFeiraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelQuartaFeiraLayout.createSequentialGroup()
                .addContainerGap(28, Short.MAX_VALUE)
                .addGroup(jPanelQuartaFeiraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jRadioButtonSeisQuarta, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jRadioButtonSeteQuarta, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jRadioButtonDezesseisQuarta, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jRadioButtonDezesseteQuarta, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jRadioButtonDezoitoQuarta, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jRadioButtonDezenoveQuarta, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jRadioButtonOitoQuarta, javax.swing.GroupLayout.Alignment.TRAILING))
                .addContainerGap())
        );
        jPanelQuartaFeiraLayout.setVerticalGroup(
            jPanelQuartaFeiraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelQuartaFeiraLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jRadioButtonSeisQuarta)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jRadioButtonSeteQuarta)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jRadioButtonOitoQuarta)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jRadioButtonDezesseisQuarta)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jRadioButtonDezesseteQuarta)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jRadioButtonDezoitoQuarta)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jRadioButtonDezenoveQuarta))
        );

        jPanelQuintaFeira.setBackground(new java.awt.Color(255, 255, 255));
        jPanelQuintaFeira.setBorder(javax.swing.BorderFactory.createTitledBorder("Quinta - feira"));
        jPanelQuintaFeira.setPreferredSize(new java.awt.Dimension(105, 209));

        jRadioButtonSeisQuinta.setBackground(new java.awt.Color(255, 255, 255));
        jRadioButtonSeisQuinta.setText("06:00h");

        jRadioButtonSeteQuinta.setBackground(new java.awt.Color(255, 255, 255));
        jRadioButtonSeteQuinta.setText("07:00h");

        jRadioButtonOitoQuinta.setBackground(new java.awt.Color(255, 255, 255));
        jRadioButtonOitoQuinta.setText("08:00h");

        jRadioButtonDezesseisQuinta.setBackground(new java.awt.Color(255, 255, 255));
        jRadioButtonDezesseisQuinta.setText("16:00h");

        jRadioButtonDezesseteQuinta.setBackground(new java.awt.Color(255, 255, 255));
        jRadioButtonDezesseteQuinta.setText("17:00h");

        jRadioButtonDezoitoQuinta.setBackground(new java.awt.Color(255, 255, 255));
        jRadioButtonDezoitoQuinta.setText("18:00h");

        jRadioButtonDezenoveQuinta.setBackground(new java.awt.Color(255, 255, 255));
        jRadioButtonDezenoveQuinta.setText("19:00h");

        javax.swing.GroupLayout jPanelQuintaFeiraLayout = new javax.swing.GroupLayout(jPanelQuintaFeira);
        jPanelQuintaFeira.setLayout(jPanelQuintaFeiraLayout);
        jPanelQuintaFeiraLayout.setHorizontalGroup(
            jPanelQuintaFeiraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelQuintaFeiraLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanelQuintaFeiraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jRadioButtonSeisQuinta, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jRadioButtonDezesseteQuinta, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jRadioButtonDezoitoQuinta, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jRadioButtonSeteQuinta, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jRadioButtonOitoQuinta, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jRadioButtonDezesseisQuinta, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jRadioButtonDezenoveQuinta, javax.swing.GroupLayout.Alignment.TRAILING))
                .addGap(366, 366, 366))
        );
        jPanelQuintaFeiraLayout.setVerticalGroup(
            jPanelQuintaFeiraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelQuintaFeiraLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jRadioButtonSeisQuinta)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jRadioButtonSeteQuinta)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jRadioButtonOitoQuinta)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jRadioButtonDezesseisQuinta)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jRadioButtonDezesseteQuinta)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jRadioButtonDezoitoQuinta)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jRadioButtonDezenoveQuinta))
        );

        jPanelSextaFeira.setBackground(new java.awt.Color(255, 255, 255));
        jPanelSextaFeira.setBorder(javax.swing.BorderFactory.createTitledBorder("Sexta - feira"));
        jPanelSextaFeira.setPreferredSize(new java.awt.Dimension(105, 209));

        jRadioButtonSeisSexta.setBackground(new java.awt.Color(255, 255, 255));
        jRadioButtonSeisSexta.setText("06:00h");
        jRadioButtonSeisSexta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButtonSeisSextaActionPerformed(evt);
            }
        });

        jRadioButtonSeteSexta.setBackground(new java.awt.Color(255, 255, 255));
        jRadioButtonSeteSexta.setText("07:00h");

        jRadioButtonOitoSexta.setBackground(new java.awt.Color(255, 255, 255));
        jRadioButtonOitoSexta.setText("08:00h");

        jRadioButtonDezesseisSexta.setBackground(new java.awt.Color(255, 255, 255));
        jRadioButtonDezesseisSexta.setText("16:00h");

        jRadioButtonDezesseteSexta.setBackground(new java.awt.Color(255, 255, 255));
        jRadioButtonDezesseteSexta.setText("17:00h");

        jRadioButtonDezoitoSexta.setBackground(new java.awt.Color(255, 255, 255));
        jRadioButtonDezoitoSexta.setText("18:00h");

        jRadioButtonDezenoveSexta.setBackground(new java.awt.Color(255, 255, 255));
        jRadioButtonDezenoveSexta.setText("19:00h");

        javax.swing.GroupLayout jPanelSextaFeiraLayout = new javax.swing.GroupLayout(jPanelSextaFeira);
        jPanelSextaFeira.setLayout(jPanelSextaFeiraLayout);
        jPanelSextaFeiraLayout.setHorizontalGroup(
            jPanelSextaFeiraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelSextaFeiraLayout.createSequentialGroup()
                .addContainerGap(28, Short.MAX_VALUE)
                .addGroup(jPanelSextaFeiraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jRadioButtonSeisSexta, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jRadioButtonSeteSexta, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jRadioButtonOitoSexta, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jRadioButtonDezesseisSexta, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jRadioButtonDezesseteSexta, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jRadioButtonDezoitoSexta, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jRadioButtonDezenoveSexta, javax.swing.GroupLayout.Alignment.TRAILING))
                .addContainerGap())
        );
        jPanelSextaFeiraLayout.setVerticalGroup(
            jPanelSextaFeiraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelSextaFeiraLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jRadioButtonSeisSexta)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jRadioButtonSeteSexta)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jRadioButtonOitoSexta)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jRadioButtonDezesseisSexta)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jRadioButtonDezesseteSexta)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jRadioButtonDezoitoSexta)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jRadioButtonDezenoveSexta))
        );

        jFormattedTextFieldDataMatricula.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jFormattedTextFieldDataMatriculaActionPerformed(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Arial", 1, 11)); // NOI18N
        jLabel6.setText("Data Matrícula");

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));

        botaoSalvar.setFont(new java.awt.Font("Arial Rounded MT Bold", 1, 11)); // NOI18N
        botaoSalvar.setText("Cadastrar");
        botaoSalvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoSalvarActionPerformed(evt);
            }
        });

        botaoListar.setFont(new java.awt.Font("Arial Rounded MT Bold", 1, 11)); // NOI18N
        botaoListar.setText("Ir Para Lista de Clientes Cadastrados");
        botaoListar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoListarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(botaoSalvar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(botaoListar)
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(botaoListar)
                    .addComponent(botaoSalvar))
                .addContainerGap())
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(15, 15, 15)
                        .addComponent(campoImagemCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(campoNome, javax.swing.GroupLayout.PREFERRED_SIZE, 340, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel5)
                                    .addComponent(campoRua, javax.swing.GroupLayout.PREFERRED_SIZE, 340, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel7)
                                    .addComponent(campoTelefone, javax.swing.GroupLayout.PREFERRED_SIZE, 188, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(campoNumero, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(campoEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 343, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel2)
                                    .addComponent(jLabel4))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(jLabel3)
                                        .addGap(163, 163, 163)
                                        .addComponent(jLabel6))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGap(212, 212, 212)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel8)
                                            .addComponent(jFormattedTextFieldDataMatricula, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(campoBairro, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(jLabelHorarios, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jPanelSegundaFeira, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanelTercaFeira, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanelQuartaFeira, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanelQuintaFeira, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanelSextaFeira, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 121, Short.MAX_VALUE)
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3)
                            .addComponent(jLabel6))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(campoNome, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(campoTelefone, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jFormattedTextFieldDataMatricula, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(jLabel5)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                            .addComponent(campoRua, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(campoNumero, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addComponent(jLabel7)))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(3, 3, 3)
                                .addComponent(jLabel8)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(campoBairro, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel4)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(campoEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(47, 47, 47)
                        .addComponent(campoImagemCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 21, Short.MAX_VALUE)
                .addComponent(jLabelHorarios, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jPanelQuintaFeira, javax.swing.GroupLayout.PREFERRED_SIZE, 197, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jPanelTercaFeira, javax.swing.GroupLayout.PREFERRED_SIZE, 204, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jPanelQuartaFeira, javax.swing.GroupLayout.PREFERRED_SIZE, 204, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jPanelSextaFeira, javax.swing.GroupLayout.PREFERRED_SIZE, 197, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jPanelSegundaFeira, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                    .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(25, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 1046, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 516, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jRadioButtonSeisSextaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButtonSeisSextaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jRadioButtonSeisSextaActionPerformed

    private void jRadioButtonDezoitoSegundaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButtonDezoitoSegundaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jRadioButtonDezoitoSegundaActionPerformed

    private void jRadioButtonSeisSegundaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButtonSeisSegundaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jRadioButtonSeisSegundaActionPerformed

    private void campoImagemClienteMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_campoImagemClienteMouseClicked
        if (evt.getClickCount() == 2) {
            gerenteDeImagens.escolherImagem(campoImagemCliente);

        }

        // TODO add your handling code here:
    }//GEN-LAST:event_campoImagemClienteMouseClicked

    private void campoNomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_campoNomeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_campoNomeActionPerformed

    private void campoFemininoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_campoFemininoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_campoFemininoActionPerformed

    private void botaoListarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoListarActionPerformed
        Cliente cliente = new Cliente();
        // TODO add your handling code here:
        ListaClientesGUI telaListarClientes = new ListaClientesGUI();
        telaListarClientes.setVisible(true);
        dispose();
    }//GEN-LAST:event_botaoListarActionPerformed

    private void botaoSalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoSalvarActionPerformed
        Cliente cliente = new Cliente();
        cliente.setNome(campoNome.getText());
        cliente.setEmail(campoEmail.getText());
        cliente.setTelefone(campoTelefone.getText());
        cliente.setRua(campoRua.getText());
        cliente.setNumero(campoNumero.getText());
        cliente.setBairro(campoBairro.getText());
        cliente.setImagem(gerenteDeImagens.getUrlImagem());
        if (campoMasculino.isSelected()) {
            cliente.setSexo("Masculino");
        } else if (campoFeminino.isSelected()) {
            cliente.setSexo("Feminino");
        }
        clienteDAO.saveOrUpdate(cliente);

        //Atualisar Lista
        listaClientes = clienteDAO.getAll();
       // CarregarTabelaClientes();
//        campoNome.setText("");
//        campoEmail.setText("");
//        campoTelefone.setText("");
//        campoRua.setText("");
//        campoNumero.setText("");
//        campoBairro.setText("");
        campoImagemCliente.setText("");

        // TODO add your handling code here:
    }//GEN-LAST:event_botaoSalvarActionPerformed

    private void jFormattedTextFieldDataMatriculaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jFormattedTextFieldDataMatriculaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jFormattedTextFieldDataMatriculaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ClienteGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ClienteGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ClienteGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ClienteGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {
                    new ClienteGUI().setVisible(true);
                } catch (ClassNotFoundException ex) {
                    Logger.getLogger(ClienteGUI.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        });
    }

//    public void CarregarTabelaClientes() {
//        modelo = new DefaultTableModel();
//        modelo.addColumn("Nome");
//        modelo.addColumn("Telefone");
//        modelo.addColumn("E-mail");
//        modelo.addColumn("Sexo");
//
//        for (int i = 0; i < listaClientes.size(); i++) {
//            Object linha[] = new Object[]{
//                listaClientes.get(i).getNome(),
//                listaClientes.get(i).getTelefone(),
//                listaClientes.get(i).getEmail(),
//                listaClientes.get(i).getSexo(),
//                listaClientes.get(i).getRua(),
//                listaClientes.get(i).getNumero(),
//                listaClientes.get(i).getBairro(),
//                listaClientes.get(i).getImagem()};
//
//            modelo.addRow(linha);
////            jTable1.addRowSelectionInterval(i, i);
//
//        }
////        jTable1.getModel().
//        jTable1.setModel(modelo);
//    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botaoListar;
    private javax.swing.JButton botaoSalvar;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.ButtonGroup buttonGroup3;
    private javax.swing.ButtonGroup buttonGroup4;
    private javax.swing.ButtonGroup buttonGroup5;
    private javax.swing.ButtonGroup buttonGroup6;
    private javax.swing.JTextField campoBairro;
    private javax.swing.JTextField campoEmail;
    private javax.swing.JRadioButton campoFeminino;
    private javax.swing.JLabel campoImagemCliente;
    private javax.swing.JRadioButton campoMasculino;
    private javax.swing.JTextField campoNome;
    private javax.swing.JTextField campoNumero;
    private javax.swing.JTextField campoRua;
    private javax.swing.JTextField campoTelefone;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JFormattedTextField jFormattedTextFieldDataMatricula;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabelHorarios;
    public javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanelQuartaFeira;
    private javax.swing.JPanel jPanelQuintaFeira;
    private javax.swing.JPanel jPanelSegundaFeira;
    private javax.swing.JPanel jPanelSextaFeira;
    private javax.swing.JPanel jPanelTercaFeira;
    private javax.swing.JRadioButton jRadioButtonDezenoveQuarta;
    private javax.swing.JRadioButton jRadioButtonDezenoveQuinta;
    private javax.swing.JRadioButton jRadioButtonDezenoveSegunda;
    private javax.swing.JRadioButton jRadioButtonDezenoveSexta;
    private javax.swing.JRadioButton jRadioButtonDezenoveTerca;
    private javax.swing.JRadioButton jRadioButtonDezesseisQuarta;
    private javax.swing.JRadioButton jRadioButtonDezesseisQuinta;
    private javax.swing.JRadioButton jRadioButtonDezesseisSegunda;
    private javax.swing.JRadioButton jRadioButtonDezesseisSexta;
    private javax.swing.JRadioButton jRadioButtonDezesseisTerca;
    private javax.swing.JRadioButton jRadioButtonDezesseteQuarta;
    private javax.swing.JRadioButton jRadioButtonDezesseteQuinta;
    private javax.swing.JRadioButton jRadioButtonDezesseteSegunda;
    private javax.swing.JRadioButton jRadioButtonDezesseteSexta;
    private javax.swing.JRadioButton jRadioButtonDezesseteTerca;
    private javax.swing.JRadioButton jRadioButtonDezoitoQuarta;
    private javax.swing.JRadioButton jRadioButtonDezoitoQuinta;
    private javax.swing.JRadioButton jRadioButtonDezoitoSegunda;
    private javax.swing.JRadioButton jRadioButtonDezoitoSexta;
    private javax.swing.JRadioButton jRadioButtonDezoitoTerca;
    private javax.swing.JRadioButton jRadioButtonOitoQuarta;
    private javax.swing.JRadioButton jRadioButtonOitoQuinta;
    private javax.swing.JRadioButton jRadioButtonOitoSegunda;
    private javax.swing.JRadioButton jRadioButtonOitoSexta;
    private javax.swing.JRadioButton jRadioButtonOitoTerca;
    private javax.swing.JRadioButton jRadioButtonSeisQuarta;
    private javax.swing.JRadioButton jRadioButtonSeisQuinta;
    private javax.swing.JRadioButton jRadioButtonSeisSegunda;
    private javax.swing.JRadioButton jRadioButtonSeisSexta;
    private javax.swing.JRadioButton jRadioButtonSeisTerca;
    private javax.swing.JRadioButton jRadioButtonSeteQuarta;
    private javax.swing.JRadioButton jRadioButtonSeteQuinta;
    private javax.swing.JRadioButton jRadioButtonSeteSegunda;
    private javax.swing.JRadioButton jRadioButtonSeteSexta;
    private javax.swing.JRadioButton jRadioButtonSeteTerca;
    // End of variables declaration//GEN-END:variables
//    private javax.swing.JTextField campoRua;
//    private javax.swing.JTextField campoNumero;
//    private javax.swing.JTextField campoBairro;
}
