
package gui;

import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author Julio
 */


public class TelaLoginGUI extends javax.swing.JFrame {

    /**
     * Creates new form ListaClientesGUI
     */
    public TelaLoginGUI() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabelUsuario = new javax.swing.JLabel();
        jLabelSenha = new javax.swing.JLabel();
        jTextFieldUsuario = new javax.swing.JTextField();
        jPasswordFieldSenha = new javax.swing.JPasswordField();
        jButtonAcessar = new javax.swing.JButton();
        jButtonSair = new javax.swing.JButton();
        jButtonCancelar = new javax.swing.JButton();
        jLabelUsuarioLogin = new javax.swing.JLabel();
        jTextFieldUsuarioLogin = new javax.swing.JTextField();
        jPasswordFieldUsuarioSenhaLogin = new javax.swing.JPasswordField();
        jLabelUsuarioSenhaLogin = new javax.swing.JLabel();
        jButtonEntrar = new javax.swing.JButton();
        jLabelFundoLogin = new javax.swing.JLabel();

        jLabelUsuario.setText("Usuário:");

        jLabelSenha.setText("Senha:");

        jButtonAcessar.setText("Acessar");
        jButtonAcessar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAcessarActionPerformed(evt);
            }
        });

        jButtonSair.setText("Sair");
        jButtonSair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSairActionPerformed(evt);
            }
        });

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jButtonCancelar.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButtonCancelar.setText("Sair");
        getContentPane().add(jButtonCancelar);
        jButtonCancelar.setBounds(450, 140, 90, 40);

        jLabelUsuarioLogin.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabelUsuarioLogin.setText("Usuário:");
        getContentPane().add(jLabelUsuarioLogin);
        jLabelUsuarioLogin.setBounds(270, 60, 60, 10);

        jTextFieldUsuarioLogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldUsuarioLoginActionPerformed(evt);
            }
        });
        getContentPane().add(jTextFieldUsuarioLogin);
        jTextFieldUsuarioLogin.setBounds(330, 50, 210, 30);
        getContentPane().add(jPasswordFieldUsuarioSenhaLogin);
        jPasswordFieldUsuarioSenhaLogin.setBounds(330, 90, 210, 30);

        jLabelUsuarioSenhaLogin.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabelUsuarioSenhaLogin.setText("Senha:");
        getContentPane().add(jLabelUsuarioSenhaLogin);
        jLabelUsuarioSenhaLogin.setBounds(270, 100, 50, 15);

        jButtonEntrar.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButtonEntrar.setText("Acessar");
        jButtonEntrar.setMaximumSize(new java.awt.Dimension(55, 23));
        jButtonEntrar.setMinimumSize(new java.awt.Dimension(55, 23));
        jButtonEntrar.setPreferredSize(new java.awt.Dimension(55, 23));
        jButtonEntrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonEntrarActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonEntrar);
        jButtonEntrar.setBounds(330, 140, 90, 40);

        jLabelFundoLogin.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imgs/Logo.jpg"))); // NOI18N
        getContentPane().add(jLabelFundoLogin);
        jLabelFundoLogin.setBounds(-4, 0, 560, 203);

        setSize(new java.awt.Dimension(572, 242));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonAcessarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAcessarActionPerformed
        try {
            // TODO add your handling code here:
            ClienteGUI telaCadastro = new ClienteGUI();
            telaCadastro.setVisible(true);
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(TelaLoginGUI.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jButtonAcessarActionPerformed

    private void jButtonSairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSairActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonSairActionPerformed

    private void jTextFieldUsuarioLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldUsuarioLoginActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldUsuarioLoginActionPerformed

    private void jButtonEntrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonEntrarActionPerformed
        try {
            // TODO add your handling code here:
            ClienteGUI telaCadastro = new ClienteGUI();
            telaCadastro.setVisible(true);
            dispose();
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(TelaLoginGUI.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        
    }//GEN-LAST:event_jButtonEntrarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaLoginGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaLoginGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaLoginGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaLoginGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaLoginGUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonAcessar;
    private javax.swing.JButton jButtonCancelar;
    private javax.swing.JButton jButtonEntrar;
    private javax.swing.JButton jButtonSair;
    private javax.swing.JLabel jLabelFundoLogin;
    private javax.swing.JLabel jLabelSenha;
    private javax.swing.JLabel jLabelUsuario;
    private javax.swing.JLabel jLabelUsuarioLogin;
    private javax.swing.JLabel jLabelUsuarioSenhaLogin;
    private javax.swing.JPasswordField jPasswordFieldSenha;
    private javax.swing.JPasswordField jPasswordFieldUsuarioSenhaLogin;
    private javax.swing.JTextField jTextFieldUsuario;
    private javax.swing.JTextField jTextFieldUsuarioLogin;
    // End of variables declaration//GEN-END:variables
}
